//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroTile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TileManiacAllowDirect16x16TilesGIFEditing {
            get {
                return ((bool)(this["TileManiacAllowDirect16x16TilesGIFEditing"]));
            }
            set {
                this["TileManiacAllowDirect16x16TilesGIFEditing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TileManiacPromptForChoiceOnImageWrite {
            get {
                return ((bool)(this["TileManiacPromptForChoiceOnImageWrite"]));
            }
            set {
                this["TileManiacPromptForChoiceOnImageWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TileManiacClassicMode {
            get {
                return ((bool)(this["TileManiacClassicMode"]));
            }
            set {
                this["TileManiacClassicMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TileManiacShowGrid {
            get {
                return ((bool)(this["TileManiacShowGrid"]));
            }
            set {
                this["TileManiacShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TileManiacRenderViewerSetting {
            get {
                return ((int)(this["TileManiacRenderViewerSetting"]));
            }
            set {
                this["TileManiacRenderViewerSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TileManiacListSetting {
            get {
                return ((int)(this["TileManiacListSetting"]));
            }
            set {
                this["TileManiacListSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TileManiacViewAppearanceMode {
            get {
                return ((int)(this["TileManiacViewAppearanceMode"]));
            }
            set {
                this["TileManiacViewAppearanceMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TileManiacMirrorMode {
            get {
                return ((bool)(this["TileManiacMirrorMode"]));
            }
            set {
                this["TileManiacMirrorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TileManiacWindowAlwaysOnTop {
            get {
                return ((bool)(this["TileManiacWindowAlwaysOnTop"]));
            }
            set {
                this["TileManiacWindowAlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TileManiacEnableWindowsClipboard {
            get {
                return ((bool)(this["TileManiacEnableWindowsClipboard"]));
            }
            set {
                this["TileManiacEnableWindowsClipboard"] = value;
            }
        }
    }
}
